# Generated by Django 4.2.16 on 2024-11-07 19:51

import django.core.validators
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(3), users.validators.IsAlphaValidator()])),
                ('last_name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(3), users.validators.IsAlphaValidator()])),
            ],
        ),
    ]
