# Generated by Django 4.2.16 on 2024-11-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='users',
            name='info',
            field=models.TextField(default='My info'),
        ),
        migrations.AddField(
            model_name='users',
            name='last_name',
            field=models.CharField(default='Last_name', max_length=30),
        ),
    ]
