# Generated by Django 4.2.16 on 2024-12-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='owner',
            field=models.CharField(max_length=100),
        ),
    ]
