# Generated by Django 4.2.16 on 2024-12-06 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_users_email'),
        ('clubs', '0004_club_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='users.users'),
        ),
    ]
